site_name: '1º Programacion (CFGS Desarrollo de Aplicaciones Multiplataforma)'
site_url: https://martinezpenya.es/1DAMProgramacion/
site_description: 'Apuntes de Programación para 1º del CFGS Desarrollo de Aplicaciones Multiplataforma (DAM). Incluye Java, POO, bases de datos, JavaFX y más.'
site_author: 'David Martínez Peña'
repo_url: https://github.com/martinezpenya/1DAMProgramacion
edit_uri: edit/main/docs

nav:
  - UD00:
    - Información importante: index.md
  - UD01:
    - Elementos de un programa informático: UD01/UD01_ES.md
    - Ejercicios: UD01/UD01_ejercicios_ES.md
    - Talleres:
      - T01 NoMachine: UD01/UD01_T01_NoMachine.md
      - T02 JDK e IDE: UD01/UD01_T02_JDK&IDE.md
      - T03 GitHub: UD01/UD01_T03_GitHub.md
      - T04 Markdown: UD01/UD01_T04_Markdown.md
  - UD02:
    - Utilización de Objetos y Clases: UD02/UD02_ES.md
    - Ejercicios: UD02/UD02_ejercicios_ES.md
    - Talleres:
      - T01 GitHub Classroom: UD02/UD02_T01_GitHubClassroom.md
  - UD03:
    - Estructuras de control y Excepciones: UD03/UD03_ES.md
    - Ejercicios: UD03/UD03_ejercicios_ES.md
    - Talleres:
      - T01 GitHub Classroom: UD03/UD03_T01_GitHubClassroom.md
      - T02 Acepta el reto: UD03/UD03_T02_AceptaElReto.md
  - UD04:
    - Estructuras de datos Arrays y matrices. Recursividad: UD04/UD04_ES.md
    - Anexo Cheatsheet String: UD04/UD04_anexo_ES.md
    - Ejercicios: UD04/UD04_ejercicios_ES.md
    - Talleres:
      - T01 GitHub Classroom: UD04/UD04_T01_GitHubClassroom.md
  - UD05:
    - Desarrollo de clases: UD05/UD05_ES.md
    - Anexo Wrappers y Fechas: UD05/UD05_anexo_ES.md
    - Ejercicios: UD05/UD05_ejercicios_ES.md
    - Talleres:
      - T01 GitHub Classroom: UD05/UD05_T01_GitHubClassroom.md
  - UD06:
    - Lectura y escritura de información: UD06/UD06_ES.md
    - Comparativa CRUD: UD06/UD06_comparativa_CRUD.md
    - Ejercicios: UD06/UD06_ejercicios_ES.md
    - Talleres:
      - T01 GitHub Classroom: UD06/UD06_T01_GitHubClassroom.md
      - T02 Sockets en AWS: UD06/UD06_T02_Sockets_ES.md
  - UD07:
    - Colecciones: UD07/UD07_ES.md
    - Ejercicios: UD07/UD07_ejercicios_ES.md
    - Talleres:
      - T01 GitHub Classroom: UD07/UD07_T01_GitHubClassroom.md
  - UD08:
    - Composición, Herencia y Polimorfismo: UD08/UD08_ES.md
    - Ejercicios: UD08/UD08_ejercicios_ES.md
    - Talleres:
      - T01 GitHub Classroom: UD08/UD08_T01_GitHubClassroom.md
      - T02 Librerias Jar vs Maven: UD08/UD08_T02_LibreriasMavenJar_ES.md
      - T03 Json vs YAML: UD08/UD08_T03_JSON&YAML_ES.md
  - UD09:
    - Interfaz gráfica: UD09/UD09_ES.md
    - Ejercicios: UD09/UD09_ejercicios_ES.md
    - Talleres:
      - T01 GitHub Classroom: UD09/UD09_T01_GitHubClassroom.md
      - T02 SceneBuilder & IntelliJ: UD09/UD09_T02_SceneBuilder_IntelliJ_ES.md
      - T03 Proyecto JavaFX Maven: UD09/UD09_T03_ProyectoJavaFXMaven_ES.md
      - T04 Calculadora JavaFX: UD09/UD09_T04_Calculadora_en_JavaFX_IntelliJ_ES.md
  - UD10:
    - BB.DD. relacionales: UD10/UD10_ES.md
    - Ejercicios: UD10/UD10_ejercicios_ES.md
    - Talleres:
      - T01 GitHub Classroom: UD10/UD10_T01_GitHubClassroom.md
      - T02 SceneBuilder & IntelliJ: UD10/UD10_T02_Conectores_ES.md
      - T03 Proyecto JavaFX Maven: UD10/UD10_T03_AWS_IntelliJ_ES.md
      - T04 Calculadora JavaFX: UD10/UD10_T04_DAO_ES.md
  - UD11:
    - BB.DD. OO: UD11/UD11_ES.md
    - Ejercicios: UD11/UD11_ejercicios_ES.md
    - Talleres:
      - T01 GitHub Classroom: UD11/UD11_T01_GitHubClassroom.md
      - T02 SceneBuilder & IntelliJ: UD11/UD11_T02_ObjectDB_ES.md
      - T03 Proyecto JavaFX Maven: UD11/UD11_T03_CRUD_ObjectDB_ES.md
  - Sobre mi: sobremi.md
  - Fuentes de información: fuentes.md

theme:
  name: material
  language: es
  features:
    - header.autohide
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.anotate
    #- content.tabs.link
    - toc.follow
    - toc.integrate
    - navigation.top
    #- navigation.tracking
    - navigation.footer
    #- navigation.indexes
  icon:
    logo: material/language-java
  favicon: assets/favicon.ico
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/brands/java
      quote: fontawesome/solid/quote-left
  favicon: assets/favicon.ico
#  features:
#    - navigation.footer
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: light blue  
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
extra_css:
  - css/extra.css
markdown_extensions:
  - sane_lists
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      #anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex
extra_javascript:
  - ./js/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js
extra:
  search:
    language: es
  social:
    - icon: simple/youtube
      link: https://youtube.com/@martinezpenya
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/martinezpenya
    - icon: fontawesome/brands/github
      link: https://github.com/martinezpenya
    - icon: fontawesome/solid/mug-saucer
      link: https://buymeacoffee.com/martinezpenya
      name: Buy me a coffee
#  consent:
#    title: Consentimiento de cookie
#    description: >-
#      Esta página de apuntes utiliza cookies para reconocer las visitas, medir la #efectividad de la documentación
#      y averiguar si encuentras aquello que buscas o cómo has llegado a estos apuntes.
#      Con tu consentimiento, me ayudas a mejorar estos materiales.

copyright: "© 2025 David Martínez licensed under CC BY-NC-SA 4.0"

plugins:
    - mkdocs-video
    # - offline  # Comentado para permitir la generación del sitemap para SEO
    - search
    - git-revision-date-localized:
        fallback_to_build_date: true
    - minify:
        minify_html: true
    - extra-sass
    - with-pdf:
        author: David Martinez Peña
        #copyright: (www.martinezpenya.es)
        #
        cover: true
        #cover_logo: docs/assets/images/aws_cast.png
        cover_logo: https://martinezpenya.es/1DAMProgramacion/assets/portada.png
        back_cover: true
        #cover_title: TITLE TEXT
        cover_subtitle: IES Eduardo Primo Marques (Carlet)
        #custom_template_path: templates
        #
        toc_title: Indice de contenidos
        #heading_shift: false
        toc_level: 3
        ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:/assets/LoadMavenChanges.png
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        output_path: docs/Libro.pdf
    #     #enabled_if_env: ENABLE_PDF_EXPORT
    #     #
    #     #debug_html: true
    #     show_anchors: true
    #     verbose: true
